export interface RemoteEditPanelMessageHandlers {
  getActiveConnectionId(): string | undefined;
  getActivePath(): string;
  onReady(): Promise<void>;
  saveConnection(payload: any): Promise<void>;
  pickPrivateKeyPath(): Promise<void>;
  pickCaCertificatePath(): Promise<void>;
  deleteConnection(payload: any): Promise<void>;
  renameConnection(payload: any): Promise<void>;
  reorderConnections(payload: any): Promise<void>;
  createConnectionGroup(payload: any): Promise<void>;
  renameConnectionGroup(payload: any): Promise<void>;
  deleteConnectionGroup(payload: any): Promise<void>;
  syncPersistentStorage(payload: any): Promise<void>;
  requestImportConnectionsSettings(): Promise<void>;
  exportConnectionsSettings(payload: any): Promise<void>;
  importConnectionsSettings(payload: any): Promise<void>;
  connect(payload: any): Promise<void>;
  cancelConnection(payload?: any): Promise<void>;
  disconnect(connectionId: string): Promise<void>;
  switchSession(connectionId: string): Promise<void>;
  reorderSessions(payload: any): void;
  enableSudoMode(): Promise<void>;
  disableSudoMode(connectionId: string): void;
  listDirectory(remotePath: string, options?: { forceRefresh?: boolean }): Promise<void>;
  requestBreadcrumbDirectories(payload: any): Promise<void>;
  openParent(): Promise<void>;
  openEntry(payload: any): Promise<void>;
  openEntries(payload: any): Promise<void>;
  openEntriesReadOnly(payload: any): Promise<void>;
  compareSelectedEntries(payload: any): Promise<void>;
  openPath(payload: any): Promise<void>;
  addRemotePathFavorite(payload: any): Promise<void>;
  removeRemotePathFavorite(payload: any): Promise<void>;
  requestCreateFile(payload: any): Promise<void>;
  requestCreateDirectory(payload: any): Promise<void>;
  requestMakeCopy(payload: any): Promise<void>;
  requestCalculateChecksums(payload: any): Promise<void>;
  requestRenameEntry(payload: any): Promise<void>;
  requestDeleteEntry(payload: any): Promise<void>;
  requestDeleteEntries(payload: any): Promise<void>;
  requestUploadEntries(payload: any): Promise<void>;
  requestDroppedUploadEntries(payload: any): Promise<void>;
  beginDroppedUploadEntries(payload: any): Promise<void>;
  writeDroppedUploadChunk(payload: any): Promise<void>;
  finishDroppedUploadEntries(payload: any): Promise<void>;
  cancelDroppedUploadEntries(payload: any): Promise<void>;
  requestDownloadEntries(payload: any): Promise<void>;
  requestCompressArchive(payload: any): Promise<void>;
  cancelTransfer(payload?: any): Promise<void>;
  removeQueuedTransfer(payload: any): void;
  requestSetPermissions(payload: any): Promise<void>;
  requestChangeOwnerGroup(payload: any): Promise<void>;
  requestOwnerGroupSuggestions(payload: any): Promise<void>;
  requestRunRemoteCommand(payload: any): Promise<void>;
  requestOpenSshTerminal(payload: any): Promise<void>;
  requestOpenLogViewer(payload: any): Promise<void>;
  requestServerDashboard(payload: any): Promise<void>;
  requestServerServiceDetails(payload: any): Promise<void>;
  requestServerServiceAction(payload: any): Promise<void>;
  requestServerProcessDetails(payload: any): Promise<void>;
  requestServerProcessAction(payload: any): Promise<void>;
  requestServerScheduledJobAction(payload: any): Promise<void>;
  requestPortForwardState(payload: any): Promise<void>;
  startPortForward(payload: any): Promise<void>;
  stopPortForward(payload: any): Promise<void>;
  requestRemoteSearchState(): void;
  browseRemoteSearchScope(payload: any): Promise<void>;
  startRemoteSearch(payload: any): Promise<void>;
  cancelRemoteSearch(): void;
  clearRemoteSearch(): void;
  stopRemoteCommand(payload: any): void;
  applyPermissions(payload: any): void;
  cancelPermissions(): void;
  showSettings(): void;
  showOutput(): void;
  copyRemotePath(payload: any): Promise<void>;
  copyStatus(payload: any): Promise<void>;
  confirmDialogResponse(payload: any): void;
  inputDialogResponse(payload: any): void;
  transferConflictResponse(payload: any): void;
  log(message: string): void;
  performanceLog(payload: any): void;
  unknown(messageType: string): void;
}
