export interface RemoteEditPanelMessageHandlers {
  getActiveConnectionId(): string | undefined;
  getActivePath(): string;
  onReady(): Promise<void>;
  saveConnection(payload: any): Promise<void>;
  pickPrivateKeyPath(): Promise<void>;
  deleteConnection(payload: any): Promise<void>;
  renameConnection(payload: any): Promise<void>;
  requestImportConnectionsSettings(): Promise<void>;
  exportConnectionsSettings(payload: any): Promise<void>;
  importConnectionsSettings(payload: any): Promise<void>;
  connect(payload: any): Promise<void>;
  cancelConnection(): Promise<void>;
  disconnect(connectionId: string): Promise<void>;
  switchSession(connectionId: string): Promise<void>;
  enableSudoMode(): Promise<void>;
  disableSudoMode(connectionId: string): void;
  listDirectory(remotePath: string): Promise<void>;
  requestBreadcrumbDirectories(payload: any): Promise<void>;
  openParent(): Promise<void>;
  openEntry(payload: any): Promise<void>;
  openEntries(payload: any): Promise<void>;
  openEntriesReadOnly(payload: any): Promise<void>;
  compareSelectedEntries(payload: any): Promise<void>;
  openPath(payload: any): Promise<void>;
  addRemotePathFavorite(payload: any): Promise<void>;
  removeRemotePathFavorite(payload: any): Promise<void>;
  requestCreateFile(payload: any): Promise<void>;
  requestCreateDirectory(payload: any): Promise<void>;
  requestMakeCopy(payload: any): Promise<void>;
  requestCalculateChecksums(payload: any): Promise<void>;
  requestRenameEntry(payload: any): Promise<void>;
  requestDeleteEntry(payload: any): Promise<void>;
  requestDeleteEntries(payload: any): Promise<void>;
  requestUploadEntries(payload: any): Promise<void>;
  requestDownloadEntries(payload: any): Promise<void>;
  requestCompressArchive(payload: any): Promise<void>;
  cancelTransfer(): Promise<void>;
  removeQueuedTransfer(payload: any): void;
  requestSetPermissions(payload: any): Promise<void>;
  requestChangeOwnerGroup(payload: any): Promise<void>;
  requestRunRemoteCommand(payload: any): Promise<void>;
  stopRemoteCommand(payload: any): void;
  applyPermissions(payload: any): void;
  cancelPermissions(): void;
  showOutput(): void;
  copyRemotePath(payload: any): Promise<void>;
  copyStatus(payload: any): Promise<void>;
  confirmDialogResponse(payload: any): void;
  transferConflictResponse(payload: any): void;
  log(message: string): void;
  unknown(messageType: string): void;
}
