import { remoteSearchResultStyles } from '../search/RemoteSearchResultStyles';
import { multiTargetStyles } from '../multiTarget/MultiTargetStyles';
import type * as vscode from 'vscode';
import { getNonce } from '../utils/webviewUtils';
import { renderMultiTargetScript } from './MultiTargetScript';

export function renderMultiTargetHtml(webview: vscode.Webview): string {
  const nonce = getNonce();
  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'nonce-${nonce}';">
<title>Multi-Target Commands & Search</title><style>${multiTargetStyles}
${remoteSearchResultStyles}
#search-fields{flex:1;min-height:0;overflow:auto;padding:6px 10px 0;display:flex;flex-direction:column;gap:5px}.search-options{display:flex;column-gap:16px;row-gap:6px;flex-wrap:wrap}.search-options label{display:flex;align-items:center;gap:6px;font-size:var(--multi-target-font-size)}.search-field{display:grid;gap:3px;min-width:0;line-height:12px;color:var(--vscode-descriptionForeground);font-size:var(--multi-target-font-size)}.search-field-heading{display:flex;align-items:center;gap:8px;min-width:0;height:12px;line-height:12px}.search-field-hint{flex:1 1 auto;margin-left:auto;min-width:0;overflow:hidden;text-align:right;text-overflow:ellipsis;white-space:nowrap;color:var(--vscode-descriptionForeground);font-size:var(--multi-target-font-size);font-weight:400}.search-field-reserved.inactive{visibility:hidden;pointer-events:none}#filename,#text-to-find{height:27px;min-height:27px;padding:3px 8px}body[data-mode="search"] #output{white-space:normal;padding:6px 0}body[data-mode="search"] #output .remote-search-empty{padding:1px 10px}#output .output-placeholder,#output .remote-search-empty{color:var(--vscode-descriptionForeground);opacity:.82;font-family:var(--vscode-font-family);font-size:var(--multi-target-font-size)}
[hidden]{display:none!important}#mode-header{background:var(--vscode-editorGroupHeader-tabsBackground,var(--vscode-sideBar-background,var(--vscode-editor-background)));border-bottom:1px solid var(--vscode-panel-border)}#mode-tabs{display:flex;align-items:center;gap:2px;min-width:0}#mode-tabs .mode-tab{height:20px;min-height:20px;padding:0 5px;border:0;border-radius:3px;background:transparent;color:var(--vscode-descriptionForeground);font-size:11px;font-weight:600;letter-spacing:.45px;line-height:20px;text-transform:uppercase}#mode-tabs .mode-tab:hover:not(:disabled){background:var(--vscode-list-hoverBackground);color:var(--vscode-foreground)}#mode-tabs .mode-tab[aria-selected="true"]{background:var(--vscode-list-inactiveSelectionBackground,var(--vscode-list-hoverBackground));color:var(--vscode-list-inactiveSelectionForeground,var(--vscode-foreground))}#mode-tabs .mode-tab[aria-selected="true"]:hover{background:var(--vscode-list-inactiveSelectionBackground,var(--vscode-list-hoverBackground));color:var(--vscode-list-inactiveSelectionForeground,var(--vscode-foreground))}.mode-tab-separator{color:var(--vscode-descriptionForeground);font-size:11px;font-weight:600;line-height:20px;opacity:.72;user-select:none}#commands-fields{display:flex;flex:1;min-height:0;flex-direction:column;padding-top:6px}#commands-fields textarea{flex:1;min-height:0}#search-fields{flex:1}#search-run{font-size:var(--multi-target-font-size)}
</style></head><body><main>
<section id="targets"><div id="targets-layout"><div id="targets-main"><div class="table-wrap"><table aria-label="Command targets"><colgroup><col style="width:24%"><col><col style="width:18%"><col style="width:58px"></colgroup><thead><tr><th>Target</th><th id="directory-heading">Working Directory</th><th>Status</th><th aria-label="Target actions"></th></tr></thead><tbody id="target-rows"></tbody></table><div id="target-empty" class="empty">Choose saved connections with Manage Targets.</div></div><div id="target-summary-row"><span id="target-summary" class="muted">No targets selected</span></div></div><aside class="target-actions-panel" aria-label="Target actions"><button id="manage" class="secondary">Manage Targets</button><button id="bulk-directory" class="secondary">Set Directory</button><button id="save-target-set" class="secondary" disabled>Save Target Set</button><button id="target-sets" class="secondary" disabled>Target Sets</button><button id="connect">Connect</button></aside></div></section>
<div id="work"><section id="command-section"><header id="mode-header"><nav id="mode-tabs" role="tablist" aria-label="Multi-Target mode"><button id="tab-commands" class="mode-tab" type="button" role="tab" aria-selected="true" tabindex="0" aria-controls="work">COMMANDS</button><span class="mode-tab-separator" aria-hidden="true">|</span><button id="tab-search" class="mode-tab" type="button" role="tab" aria-selected="false" tabindex="-1" aria-controls="work">SEARCH</button></nav><span id="mode-description">Same command for every target</span></header><div id="commands-fields" ><textarea id="command" aria-label="Command" spellcheck="false" placeholder="Enter a command or multiline script"></textarea></div><footer id="commands-footer"><button id="save-command" class="secondary">Save Command</button><button id="saved" class="secondary">Commands</button><label class="sudo"><input type="checkbox" id="sudo">Run with Sudo</label><span class="spacer"></span><button id="run" disabled>Run</button></footer><div id="search-fields"  hidden><div class="search-options"><label><input type="checkbox" id="include-subdirectories" checked>Include subdirectories</label><label><input type="checkbox" id="include-hidden-files">Include hidden files</label><label><input type="checkbox" id="case-sensitive">Case sensitive</label><label><input type="checkbox" id="search-inside-file">Search inside file</label><label><input type="checkbox" id="search-sudo">Run with Sudo</label></div><label class="search-field"><span class="search-field-heading"><span>Filename</span><span class="search-field-hint">Use wildcards: *, ?, [abc]. Separate multiple patterns with commas.</span></span><input id="filename" spellcheck="false" value="*" placeholder="*.log"></label><label id="text-to-find-field" class="search-field search-field-reserved inactive" aria-hidden="true">Text to find<input id="text-to-find" spellcheck="false"></label></div><footer id="search-footer" hidden><span class="spacer"></span><button id="search-run" disabled>Search</button></footer></section>
<div id="splitter" role="separator" aria-label="Resize Command and Results" aria-orientation="horizontal" aria-valuemin="10" aria-valuemax="80" aria-valuenow="30" tabindex="0"></div>
<section id="results"><header><h2>RESULTS</h2><span id="result-summary">No execution yet</span></header><nav id="filters" aria-label="Filter results"><button data-filter="All" class="active">All 0</button><button data-filter="Running">Running 0</button><button data-filter="Finished">Finished 0</button><button data-filter="Failed">Failed 0</button></nav>
<div id="result-table-wrap" class="table-wrap"><table aria-label="Command results"><colgroup><col style="width:35%"><col style="width:23%"><col style="width:10%"><col style="width:18%"><col style="width:14%"></colgroup><thead><tr><th>Target</th><th>Status</th><th id="result-value-heading">Exit</th><th>Duration</th><th></th></tr></thead><tbody id="result-rows"></tbody></table><div id="result-empty" class="empty">Run a command to see results.</div></div>
<div id="output-header"><span id="output-title">Output</span></div><div id="output-wrap" tabindex="0" aria-label="Selected target output"><div id="output"><span class="output-placeholder">Select a result to view its output.</span></div></div>
<footer id="result-footer"><div id="feedback" role="status" aria-live="polite" class="spacer"><span id="feedback-primary" hidden></span><span id="feedback-secondary" hidden></span></div><button id="copy-output" class="secondary" disabled>Copy Output</button><button id="copy-all-outputs" class="secondary" disabled>Copy All Outputs</button><span class="result-toolbar-separator" aria-hidden="true"></span><button id="stop-all" class="secondary" disabled>Stop All</button><button id="clear" class="secondary" disabled>Clear</button></footer></section></div>
</main>
<dialog id="manage-dialog" aria-labelledby="manage-title"><header><h2 id="manage-title">Manage Targets</h2><span id="manage-count"></span></header><div class="toolbar"><input id="search" type="search" placeholder="Search connections" aria-label="Search connections"><select id="group" aria-label="Connection group"><option value="">All Groups</option></select></div><div class="toolbar"><button id="select-visible" class="secondary">Select Visible</button><button id="deselect-visible" class="secondary">Deselect Visible</button></div><div id="manage-list"></div><footer><span class="muted spacer">SSH/SFTP saved connections</span><button id="manage-cancel" class="secondary">Cancel</button><button id="manage-save">Apply</button></footer></dialog>
<dialog id="directory-dialog" aria-labelledby="directory-title"><header><h2 id="directory-title">Set Working Directory for All Targets</h2></header><input id="bulk-path" aria-label="Working directory" placeholder="Default (SSH session directory)"><footer><span class="muted spacer">Leave empty to use Default.</span><button id="directory-cancel" class="secondary">Cancel</button><button id="directory-save">Apply</button></footer></dialog>
<dialog id="target-sets-dialog" aria-labelledby="target-sets-title"><header><h2 id="target-sets-title">Target Sets</h2><span id="target-set-count"></span></header><div class="toolbar"><input id="target-set-search" type="search" placeholder="Search target sets" aria-label="Search target sets"></div><div id="target-set-list"></div><footer><span class="muted spacer">Shared by Commands and Search.</span><button id="target-sets-close" class="secondary">Close</button></footer></dialog>
<dialog id="save-target-set-dialog" aria-labelledby="save-target-set-title"><header><h2 id="save-target-set-title">Save Target Set</h2></header><div class="save-target-set-body"><label class="save-target-set-field" for="target-set-name">Title<input id="target-set-name" type="text" maxlength="160" autocomplete="off" spellcheck="false"></label><div class="muted">Choose the connections included in this shared set and their working directories.</div><div class="target-set-editor"><table aria-label="Targets in saved set"><colgroup><col style="width:42%"><col style="width:58%"></colgroup><thead><tr><th>Target</th><th>Working Directory</th></tr></thead><tbody id="target-set-editor-rows"></tbody></table></div><div id="target-set-validation" class="target-set-validation" role="status"></div></div><footer><span class="spacer"></span><button id="target-set-cancel" class="secondary">Cancel</button><button id="target-set-save-new" class="secondary" hidden>Save New</button><button id="target-set-submit">Save</button></footer></dialog>
<dialog id="target-set-delete-dialog" aria-labelledby="target-set-delete-title"><header><h2 id="target-set-delete-title">Delete Target Set</h2></header><div id="target-set-delete-message" class="saved-delete-body"></div><footer><span class="spacer"></span><button id="target-set-delete-cancel" class="secondary">Cancel</button><button id="target-set-delete-confirm">Delete</button></footer></dialog>
<dialog id="saved-dialog" aria-labelledby="saved-title"><header><h2 id="saved-title">Commands</h2><span id="saved-count"></span></header><div class="toolbar"><input id="saved-search" type="search" placeholder="Search commands" aria-label="Search commands"></div><div id="saved-list"></div><footer><span class="muted spacer">Saved commands for the Commands tab.</span><button id="saved-close" class="secondary">Close</button></footer></dialog>
<dialog id="save-command-dialog" aria-labelledby="save-command-title"><header><h2 id="save-command-title">Save Command</h2></header><div class="save-command-body"><label class="save-command-field" for="saved-command-name">Title<input id="saved-command-name" type="text" maxlength="160" autocomplete="off" spellcheck="false"></label><label class="save-command-field" for="saved-command-body">Command<textarea id="saved-command-body" spellcheck="false"></textarea></label><div id="saved-command-validation" class="saved-command-validation" role="status"></div></div><footer><span class="spacer"></span><button id="saved-command-cancel" class="secondary">Cancel</button><button id="saved-command-submit">Save</button></footer></dialog>
<dialog id="saved-delete-dialog" aria-labelledby="saved-delete-title"><header><h2 id="saved-delete-title">Delete Command</h2></header><div id="saved-delete-message" class="saved-delete-body"></div><footer><span class="spacer"></span><button id="saved-delete-cancel" class="secondary">Cancel</button><button id="saved-delete-confirm">Delete</button></footer></dialog>
<dialog id="sudo-dialog" aria-labelledby="sudo-title"><header><h2 id="sudo-title">Sudo Passwords</h2><span id="sudo-count"></span></header><div class="sudo-dialog-body"><div class="sudo-dialog-intro">Enter the sudo password for each target. Passwords are used only for this run and are not saved.</div><label class="sudo-shared-option"><input id="sudo-shared" type="checkbox">Use the same password for all targets</label><div id="sudo-shared-field" class="sudo-shared-field" hidden><label for="sudo-shared-password">Root Password</label><div class="input-with-button"><input id="sudo-shared-password" type="password" autocomplete="off" spellcheck="false"><button id="sudo-shared-password-reveal" class="input-icon-button password-reveal-button has-tooltip" type="button" aria-label="Temporarily Show Password" data-tooltip="Hold to Show Password"><svg viewBox="0 0 16 16" aria-hidden="true"><path d="M8 3C4.3 3 1.73 6.11 1 8c.73 1.89 3.3 5 7 5s6.27-3.11 7-5c-.73-1.89-3.3-5-7-5Zm0 8.5A3.5 3.5 0 1 1 8 4.5a3.5 3.5 0 0 1 0 7Zm0-1.25A2.25 2.25 0 1 0 8 5.75a2.25 2.25 0 0 0 0 4.5Z" /></svg></button></div></div><div id="sudo-target-wrap"><table id="sudo-target-table" aria-label="Sudo passwords by target"><colgroup><col style="width:42%"><col style="width:58%"></colgroup><thead><tr><th>Target</th><th id="sudo-password-heading">Root Password</th></tr></thead><tbody id="sudo-target-rows"></tbody></table></div><div id="sudo-validation" class="sudo-validation" role="status"></div></div><footer><span class="spacer"></span><button id="sudo-cancel" class="secondary">Cancel</button><button id="sudo-run" disabled>Run</button></footer></dialog>
<dialog id="input-dialog" aria-labelledby="input-title"><header><h2 id="input-title">Multi-Target Commands & Search</h2></header><div class="input-prompt-body"><div id="input-prompt" class="input-prompt-text"></div><div id="input-value-wrap" class="input-with-button reveal-hidden"><input id="input-value" autocomplete="off" spellcheck="false"><button id="input-value-reveal" class="input-icon-button password-reveal-button has-tooltip" type="button" aria-label="Temporarily Show Password" data-tooltip="Hold to Show Password" disabled><svg viewBox="0 0 16 16" aria-hidden="true"><path d="M8 3C4.3 3 1.73 6.11 1 8c.73 1.89 3.3 5 7 5s6.27-3.11 7-5c-.73-1.89-3.3-5-7-5Zm0 8.5A3.5 3.5 0 1 1 8 4.5a3.5 3.5 0 0 1 0 7Zm0-1.25A2.25 2.25 0 1 0 8 5.75a2.25 2.25 0 0 0 0 4.5Z" /></svg></button></div><div id="input-validation" class="input-prompt-validation" role="status"></div></div><footer><span class="spacer"></span><button id="input-cancel" class="secondary">Cancel</button><button id="input-submit">OK</button></footer></dialog>
<div id="webviewTooltip" class="webview-tooltip" role="tooltip" aria-hidden="true"></div>
<div id="textEditContextMenu" class="context-menu text-edit-context-menu" role="menu" aria-label="Text Edit Actions"><button id="textContextUndo" type="button" role="menuitem">Undo</button><button id="textContextRedo" type="button" role="menuitem">Redo</button><div class="context-menu-separator" role="separator"></div><button id="textContextCut" type="button" role="menuitem">Cut</button><button id="textContextCopy" type="button" role="menuitem">Copy</button><button id="textContextPaste" type="button" role="menuitem">Paste</button><div class="context-menu-separator" role="separator"></div><button id="textContextSelectAll" type="button" role="menuitem">Select All</button></div>
<div id="outputContextMenu" class="context-menu output-context-menu" role="menu" aria-label="Output Actions"><button id="searchCopyPath" type="button" role="menuitem" hidden>Copy Path</button><button id="searchCopyName" type="button" role="menuitem" hidden>Copy Name</button><button id="outputContextCopy" type="button" role="menuitem">Copy</button></div>
<script nonce="${nonce}">${renderMultiTargetScript()}</script></body></html>`;
}
